--############### 프로젝트 실행순서 ################## 


--1. '퀵메뉴'와 '실시간 라이브방송'를 사용하기 위한 필수사항

-- 1) node.js를 설치한다 
-- 2) VS Code를 설치한다 혹은 터미널을 연다

--# 퀵메뉴(트위터, 상담, 번역기) 서버 열기
-- 2-1) vscode 혹은 터미널로 해당 프로젝트의 src/main/webapp/resources/js/node-chat 폴더를 연다
-- 3-1) node index.js 명령어 입력하여 서버 열기 (3000포트)
-- *중요*
-- webapp/resources/js/header.js의 도메인 ip주소를 localhost 혹은 본인의 ip로 변경한다
-- 예) https://192.168.10.169:3000 -> https://localhost:3000


--# 라이브방송 서버 열기
-- 2-2) 2-1과 같은 방법으로 src/main/webapp/resources/js/broadcast 폴더를 연다
-- 3-2) 아래의 명령어를 차례로 입력한다
-- npm init (엔터연속..)
-- npm install socket.io
-- npm install node-static
-- npm install nodemon
-- 설치 완료 후 npm start 명령어 입력하여 서버열기 (5571 포트)
-- *중요*
--webapp/WEB-INF/views/live 폴더의 
--  live-onair-platform.jsp / live-onair-caster.jsp / live-onair-user.jsp 의 <script> src주소
--webapp/resources/js/broadcast/js 폴더의
--  caster.js / IoConnectException.js / user.js 의 io.connect('src')의 주소를
-- localhost 혹은 본인의 ip주소로 변경하여야한다  



--2. 테이블 생성 

/*--------------	회원 테이블	-----------------*/
DROP TABLE MEMBER;
DROP SEQUENCE MEMBERSEQ;

CREATE SEQUENCE MEMBERSEQ;
CREATE TABLE MEMBER(
	MEMBER_SEQ NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(1000) NOT NULL,
	MEMBER_PW VARCHAR2(1000) NOT NULL,
	MEMBER_NAME VARCHAR2(1000) NOT NULL,
	MEMBER_PHONE VARCHAR2(100) NOT NULL,
	MEMBER_ADDR VARCHAR2(4000) NOT NULL,
	MEMBER_EMAIL VARCHAR2(1000) NOT NULL,
	MEMBER_REGDATE DATE NOT NULL,
	MEMBER_HEART NUMBER NOT NULL,
	MEMBER_ENABLED INTEGER DEFAULT 1,
	MEMBER_ROLE VARCHAR2(50) DEFAULT 'ROLE_USER' NOT NULL,
	MEMBER_VOTE NUMBER NOT NULL,
	MEMBER_IMG VARCHAR2(4000) DEFAULT '이미지' NOT NULL,
	CONSTRAINT CON_MEMBER_ID UNIQUE(MEMBER_ID)
);

/*--------------	투표 테이블	-----------------*/
DROP TABLE VOTE;

CREATE TABLE VOTE(
	VOTE_ITEM VARCHAR2(1000) NOT NULL,
	VOTE_NAME VARCHAR2(1000) NOT NULL,
	VOTE_TOTAL NUMBER DEFAULT 0 NOT NULL
);

/*-------------- 라이브 방송 테이블	-----------------*/
DROP TABLE BROADCAST;
DROP SEQUENCE BROADCASTSEQ

CREATE SEQUENCE BROADCASTSEQ;
CREATE TABLE BROADCAST(
	BROADCAST_SEQ NUMBER PRIMARY KEY, 
	BROADCAST_DATE DATE NOT NULL,
	BROADCAST_ROOM VARCHAR2(100), 
	BROADCAST_CASTER VARCHAR2(100) NOT NULL,
	BROADCAST_TITLE VARCHAR2(1000) NOT NULL,
	BROADCAST_CONTENT CLOB
);

--
INSERT INTO BROADCAST VALUES(BROADCASTSEQ.NEXTVAL, TO_DATE('2019-09-12 12:00','yyyy-mm-dd hh24:mi'), null, '아이즈(IZ)', 'THE 2ND SINGLE ALBUM TEASER' , null);
INSERT INTO BROADCAST VALUES(BROADCASTSEQ.NEXTVAL, TO_DATE('2019-09-14 12:00','yyyy-mm-dd hh24:mi'), null, 'Weki Meki', '위키미키 - Tiki-Tak(99%)M/V' , null);
INSERT INTO BROADCAST VALUES(BROADCASTSEQ.NEXTVAL, TO_DATE('2019-09-02 09:00','yyyy-mm-dd hh24:mi'), null, 'Zsoo', 'test' , null);
INSERT INTO BROADCAST VALUES(BROADCASTSEQ.NEXTVAL, TO_DATE('2019-09-15 12:54','yyyy-mm-dd hh24:mi'), null, 'THE BOYZ', '야방' , null);
INSERT INTO BROADCAST VALUES(BROADCASTSEQ.NEXTVAL, TO_DATE('2019-09-16 12:01','yyyy-mm-dd hh24:mi'), null, 'Stray Kid', '찬이의 방' , null);
INSERT INTO BROADCAST VALUES(BROADCASTSEQ.NEXTVAL, TO_DATE('2019-09-17 01:46','yyyy-mm-dd hh24:mi'), null, 'TWICE', '특별한 라이브' , null);
INSERT INTO BROADCAST VALUES(BROADCASTSEQ.NEXTVAL, TO_DATE('2019-09-02 09:00','yyyy-mm-dd hh24:mi'), null, 'Zsoo', 'test' , null);
INSERT INTO BROADCAST VALUES(BROADCASTSEQ.NEXTVAL, TO_DATE('2019-09-18 12:00','yyyy-mm-dd hh24:mi'), null, 'SMTOWN', 'SuperM : 13th-Aug-2019' , null);
INSERT INTO BROADCAST VALUES(BROADCASTSEQ.NEXTVAL, TO_DATE('2019-09-18 02:24','yyyy-mm-dd hh24:mi'), null, 'VAV', '[VAV] FM41.9Mhz 바로니의 행복한 라디오' , null);
INSERT INTO BROADCAST VALUES(BROADCASTSEQ.NEXTVAL, TO_DATE('2019-09-20 05:04','yyyy-mm-dd hh24:mi'), null, 'BLACKPINK', 'BLACKPINK-DIARIES EP.13' , null);
INSERT INTO BROADCAST VALUES(BROADCASTSEQ.NEXTVAL, TO_DATE('2019-09-20 6:09','yyyy-mm-dd hh24:mi'), null, '(G)I-DLE', '댕댕이 자매 is back!' , null);
INSERT INTO BROADCAST VALUES(BROADCASTSEQ.NEXTVAL, TO_DATE('2019-09-27 12:18','yyyy-mm-dd hh24:mi'), null, 'MAMAMOO', '[휘인] soar Making Prologue #0', null);
INSERT INTO BROADCAST VALUES(BROADCASTSEQ.NEXTVAL, TO_DATE('2019-09-28 7:31','yyyy-mm-dd hh24:mi'), null, 'KANG DANIEL', 'Good-bye no-name. Hello _____!' , null);

/*-------------- 게시판 테이블	-----------------*/
DROP SEQUENCE FREEBOARD_SEQ;
DROP TABLE FREEBOARD;

CREATE SEQUENCE FREEBOARD_SEQ;

CREATE TABLE FREEBOARD(
   FREEBOARD_NUM NUMBER PRIMARY KEY,
   FREEBOARD_ID VARCHAR2(500) NOT NULL,
   FREEBOARD_TITLE VARCHAR2(500) NOT NULL,
   FREEBOARD_CONTENT CLOB NOT NULL,
   FREEBOARD_FILE CLOB ,
   FREEBOARD_REGDATE DATE NOT NULL
);

/*-------------- 게시판 댓글 테이블	-----------------*/
DROP TABLE FREEBOARD_COMMENT;
DROP SEQUENCE FREEBOARD_COMMENT_SEQ;
DROP SEQUENCE FREEBOARD_GROUPSEQ;

CREATE SEQUENCE FREEBOARD_COMMENT_SEQ;
CREATE SEQUENCE FREEBOARD_GROUPSEQ;

CREATE TABLE FREEBOARD_COMMENT(
FREEBOARD_NUM VARCHAR2(1000) NOT NULL,
FREEBOARD_COMMENT_NUM NUMBER NOT NULL,
FREEBOARD_GROUPSEQ NUMBER NOT NULL,
FREEBOARD_GROUPNO NUMBER NOT NULL,
FREEBOARD_TITLETAP NUMBER NOT NULL,
FREEBOARD_COMMENT_CONTENT VARCHAR2(1000) NOT NULL,
FREEBOARD_COMMENT_REGDATE DATE NOT NULL,
FREEBOARD_ID VARCHAR2(1000) NOT NULL
)


/*-------------- 마켓 테이블	-----------------*/
DROP SEQUENCE MARKET_SEQ;  
DROP TABLE MARKET;

CREATE SEQUENCE MARKET_SEQ;

CREATE TABLE MARKET(
   MARKET_NUM NUMBER PRIMARY KEY,
   MARKET_ID VARCHAR2(500) NOT NULL,
   MARKET_TITLE VARCHAR2(500) NOT NULL,
   MARKET_CONTENT CLOB NOT NULL,
   MARKET_REGDATE DATE NOT NULL
);

/*-------------- 마켓 댓글 테이블	-----------------*/
DROP TABLE MARKET_COMMENT;
DROP SEQUENCE MARKET_COMMENT_SEQ;

CREATE SEQUENCE MARKET_COMMENT_SEQ;

CREATE TABLE MARKET_COMMENT(
MARKET_NUM VARCHAR2(1000) NOT NULL,
MARKET_COMMENT_NUM NUMBER NOT NULL,
MARKET_COMMENT_CONTENT VARCHAR2(1000) NOT NULL,
MARKET_COMMENT_REGDATE DATE NOT NULL,
MARKET_ID VARCHAR2(1000) NOT NULL
)


--3. src/main/resources/properties/db.properties url 포트주소 확인 
--  윈도우 : 1521 / 맥 : 59162 

