DROP SEQUENCE MARKET_SEQ;  
DROP TABLE MARKET;

CREATE SEQUENCE MARKET_SEQ;

CREATE TABLE MARKET(
   MARKET_NUM NUMBER PRIMARY KEY,
   MARKET_ID VARCHAR2(500) NOT NULL,
   MARKET_TITLE VARCHAR2(500) NOT NULL,
   MARKET_CONTENT CLOB NOT NULL,
   MARKET_REGDATE DATE NOT NULL
);

INSERT INTO MARKET
VALUES(MARKET_SEQ.NEXTVAL,'조수연','판매합니다','너무힘들어요',SYSDATE);
SELECT * FROM MARKET;