/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2019-07-27 02:56:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<title>DOL-Duck</title>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"description\" content=\"Mixtape template project\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/styles/bootstrap-4.1.2/bootstrap.min.css\">\n");
      out.write("<link href=\"resources/plugins/font-awesome-4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/plugins/OwlCarousel2-2.2.1/owl.carousel.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/plugins/OwlCarousel2-2.2.1/owl.theme.default.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/plugins/OwlCarousel2-2.2.1/animate.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/styles/main_styles.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/styles/responsive.css\">\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/home.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"super_container\">\n");
      out.write("\t\n");
      out.write("\t<!-- Header -->\n");
      out.write("\t<header class=\"header\">\n");
      out.write("\t\t<div class=\"header_content d-flex flex-row align-items-center justify-content-center\">\n");
      out.write("\t\t\t<div class=\"logo\"><a href=\"#\">DOL-Duck</a></div>\n");
      out.write("\t\t\t<div class=\"log_reg\">\n");
      out.write("\t\t\t\t<ul class=\"d-flex flex-row align-items-start justify-content-start\">\n");
      out.write("\t\t\t\t\t<li><a href=\"loginform.do\">Login</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"Join.jsp\">Register</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<nav class=\"main_nav\">\n");
      out.write("\t\t\t\t<ul class=\"d-flex flex-row align-items-start justify-content-start\">\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"index.html\">HOME</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">You Tube</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Vote</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Music Chart</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">LIVE</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Board</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Market</a>\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-item:hover\" ><a href=\"#\">Hartship</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-item:hover\" ><a href=\"#\">goodship</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"form-group has-search\">\n");
      out.write("\t\t\t\t\t\t<span class=\"fa fa-search form-control-feedback\"></span> \n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Search\">\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t\t<div class=\"hamburger ml-auto\">\n");
      out.write("\t\t\t\t<div class=\"d-flex flex-column align-items-end justify-content-between\">\n");
      out.write("\t\t\t\t\t<div></div>\n");
      out.write("\t\t\t\t\t<div></div>\n");
      out.write("\t\t\t\t\t<div></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>\n");
      out.write("\n");
      out.write("\t<!-- Menu -->\n");
      out.write("\n");
      out.write("\t<div class=\"menu\">\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div class=\"menu_overlay\"></div>\n");
      out.write("\t\t\t<div class=\"menu_container d-flex flex-column align-items-start justify-content-center\">\n");
      out.write("\t\t\t\t<div class=\"menu_log_reg\">\n");
      out.write("\t\t\t\t\t<ul class=\"d-flex flex-row align-items-start justify-content-start\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Login</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Register</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<nav class=\"menu_nav\">\n");
      out.write("\t\t\t\t\t<ul class=\"d-flex flex-column align-items-start justify-content-start\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"about.html\">About us</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"music.html\">Music</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"blog.html\">News</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"contact.html\">Contact</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</nav>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- Home -->\n");
      out.write("\n");
      out.write("\t<div class=\"home\">\n");
      out.write("\t\t<div class=\"home_slider_container\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<!-- Home Slider -->\n");
      out.write("\t\t\t<div class=\"owl-carousel owl-theme home_slider\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- Slide -->\n");
      out.write("\t\t\t\t<div class=\"owl-item\">\n");
      out.write("\t\t\t\t\t<div class=\"background_image\" style=\"background-image:url(resources/images/index.jpg)\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"home_container\">\n");
      out.write("\t\t\t\t\t\t<div class=\"home_container_inner d-flex flex-column align-items-center justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"home_content text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"home_subtitle\">New single release</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"home_title\"><h1>Love is all around</h1></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"home_link\"><a href=\"#\">Listen on Soundcloud</a></div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Slide -->\n");
      out.write("\t\t\t\t<div class=\"owl-item\">\n");
      out.write("\t\t\t\t\t<div class=\"background_image\" style=\"background-image:url(resources/images/index.jpg)\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"home_container\">\n");
      out.write("\t\t\t\t\t\t<div class=\"home_container_inner d-flex flex-column align-items-center justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"home_content text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"home_subtitle\">New single release</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"home_title\"><h1>Love is all around</h1></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"home_link\"><a href=\"#\">Listen on Soundcloud</a></div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Slide -->\n");
      out.write("\t\t\t\t<div class=\"owl-item\">\n");
      out.write("\t\t\t\t\t<div class=\"background_image\" style=\"background-image:url(resources/images/index.jpg)\"></div>\n");
      out.write("\t\t\t\t\t<div class=\"home_container\">\n");
      out.write("\t\t\t\t\t\t<div class=\"home_container_inner d-flex flex-column align-items-center justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"home_content text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"home_subtitle\">New single release</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"home_title\"><h1>Love is all around</h1></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"home_link\"><a href=\"#\">Listen on Soundcloud</a></div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- Featured Album -->\n");
      out.write("\n");
      out.write("\t<div class=\"featured_album\">\n");
      out.write("\t\t<div class=\"background_image featured_background\" style=\"background-image:url(images/featured.png)\"></div>\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 offset-lg-6\">\n");
      out.write("\t\t\t\t\t<div class=\"section_title_container\">\n");
      out.write("\t\t\t\t\t\t<div class=\"section_subtitle\">Events</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"section_title\"><h1>Featured Album</h1></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row featured_row row-lg-eq-height\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Featured Album Image -->\n");
      out.write("\t\t\t\t<div class=\"col-md-6\">\n");
      out.write("\t\t\t\t\t<div class=\"featured_album_image\">\n");
      out.write("\t\t\t\t\t\t<div class=\"image_overlay\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"background_image\" style=\"background-image:url(images/featured_album.jpg)\"></div>\n");
      out.write("\t\t\t\t\t\t<!-- <img src=\"images/featured_album.jpg\" alt=\"\"> -->\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Featured Album Player -->\n");
      out.write("\t\t\t\t<div class=\"col-md-6 featured_album_col\">\n");
      out.write("\t\t\t\t\t<div class=\"featured_album_player_container d-flex flex-column align-items-start justify-content-center\">\n");
      out.write("\t\t\t\t\t\t<div class=\"featured_album_player\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"featured_album_title_bar d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"featured_album_title_container\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"featured_album_artist\">Maria Smith</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"featured_album_title\">Love is all Around</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"featured_album_link ml-auto\"><a href=\"#\">buy it on itunes</a></div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div id=\"jplayer_1\" class=\"jp-jplayer\"></div>\n");
      out.write("\t\t\t\t\t\t\t<div id=\"jp_container_1\" class=\"jp-audio\" role=\"application\" aria-label=\"media player\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"jp-type-playlist\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"jp-playlist\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"player_details d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"jp-details\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div>playing</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-title\" aria-label=\"title\">&nbsp;</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"jp-controls-holder ml-auto\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"jp-play\" tabindex=\"0\"></button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"player_controls\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"jp-gui jp-interface d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-controls-holder time_controls d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div><div class=\"jp-current-time\" role=\"timer\" aria-label=\"time\">&nbsp;</div></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-progress\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-seek-bar\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-play-bar\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div><div class=\"jp-duration ml-auto\" role=\"timer\" aria-label=\"duration\">&nbsp;</div></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-volume-controls d-flex flex-row align-items-center justify-content-start ml-auto\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"jp-mute\" tabindex=\"0\"></button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-volume-bar\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-volume-bar-value\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"jp-no-solution\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>Update Required</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\tTo play the media you will need to either update your browser to a recent version or update your <a href=\"http://get.adobe.com/flashplayer/\" target=\"_blank\">Flash plugin</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- Shows -->\n");
      out.write("\n");
      out.write("\t<div class=\"shows\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\" style=\"z-index:10;\">\n");
      out.write("\t\t\t\t<div class=\"col\">\n");
      out.write("\t\t\t\t\t<div class=\"section_title_container\">\n");
      out.write("\t\t\t\t\t\t<div class=\"section_subtitle\">Events</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"section_title\"><h1>Upcoming Shows</h1></div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row shows_row\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- Shows List -->\n");
      out.write("\t\t\t\t<div class=\"col-lg-8 order-lg-1 order-2 shows_list_col\">\n");
      out.write("\t\t\t\t\t<div class=\"shows_list_container\">\n");
      out.write("\t\t\t\t\t\t<ul class=\"shows_list\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Show -->\n");
      out.write("\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t<div><div class=\"show_date\">18/07</div></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"show_info d-flex flex-md-row flex-column align-items-md-center align-items-start justify-content-md-start justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"show_name\"><a href=\"#\">Electric Castle Festival</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"show_location\">Cluj, Romania</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ml-auto\"><div class=\"show_shop trans_200\"><a href=\"#\">Buy Tickets</a></div></div>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Show -->\n");
      out.write("\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t<div><div class=\"show_date\">20/07</div></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"show_info d-flex flex-md-row flex-column align-items-md-center align-items-start justify-content-md-start justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"show_name\"><a href=\"#\">Ultra Music Festival</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"show_location\">Miami, USA</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ml-auto\"><div class=\"show_shop trans_200\"><a href=\"#\">Buy Tickets</a></div></div>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Show -->\n");
      out.write("\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t<div><div class=\"show_date\">03/08</div></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"show_info d-flex flex-md-row flex-column align-items-md-center align-items-start justify-content-md-start justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"show_name\"><a href=\"#\">Untold Festival</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"show_location\">Cluj, Romania</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ml-auto\"><div class=\"show_shop trans_200\"><a href=\"#\">Buy Tickets</a></div></div>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Show -->\n");
      out.write("\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t<div><div class=\"show_date\">11/08</div></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"show_info d-flex flex-md-row flex-column align-items-md-center align-items-start justify-content-md-start justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"show_name\"><a href=\"#\">Sun Kissed Festival</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"show_location\">Paris, France</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ml-auto\"><div class=\"show_shop trans_200\"><a href=\"#\">Buy Tickets</a></div></div>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Show -->\n");
      out.write("\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t<div><div class=\"show_date\">18/08</div></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"show_info d-flex flex-md-row flex-column align-items-md-center align-items-start justify-content-md-start justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"show_name\"><a href=\"#\">Spanish Festival</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"show_location\">Madrid, Spain</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ml-auto\"><div class=\"show_shop trans_200\"><a href=\"#\">Buy Tickets</a></div></div>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<!-- Show -->\n");
      out.write("\t\t\t\t\t\t\t<li class=\"d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t<div><div class=\"show_date\">25/08</div></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"show_info d-flex flex-md-row flex-column align-items-md-center align-items-start justify-content-md-start justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"show_name\"><a href=\"#\">Vikings Festival</a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"show_location\">Oslo, Norway</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"ml-auto\"><div class=\"show_shop trans_200\"><a href=\"#\">Buy Tickets</a></div></div>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Shows Image -->\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 order-lg-2 order-1\">\n");
      out.write("\t\t\t\t\t<div class=\"shows_image\">\n");
      out.write("\t\t\t\t\t\t<div class=\"image_overlay\"></div>\n");
      out.write("\t\t\t\t\t\t<img src=\"images/shows.jpg\" alt=\"https://unsplash.com/@anthonydelanoix\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- Artist -->\n");
      out.write("\n");
      out.write("\t<div class=\"artist\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Artist Image -->\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 artist_image_col\">\n");
      out.write("\t\t\t\t\t<div class=\"artist_image\">\n");
      out.write("\t\t\t\t\t\t<img src=\"images/artist.png\" alt=\"\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Artist Content -->\n");
      out.write("\t\t\t\t<div class=\"col-lg-7 offset-lg-1\">\n");
      out.write("\t\t\t\t\t<div class=\"artist_content\">\n");
      out.write("\t\t\t\t\t\t<div class=\"section_title_container\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"section_subtitle\">Events</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"section_title\"><h1>The Artist</h1></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"artist_text\">\n");
      out.write("\t\t\t\t\t\t\t<p> In vitae nisi aliquam, scelerisque leo a, volutpat sem. Vivamus rutrum dui fermentum eros hendrerit, id lobortis leo volutpat. Maecenas sollicitudin est in libero pretium interdum. Nullam volutpat dui sem, ac congue purus luctus nec. Curabitur luctus luctus erat, sit amet facilisis quam congue quis. Quisque ornare luctus erat id dignissim. Nullam ac nunc quis ex porttitor luctus.</p>\n");
      out.write("\t\t\t\t\t\t\t<p>Integer sed facilisis eros. In iaculis rhoncus velit in malesuada. In hac habitasse platea dictumst. Fusce erat ex, consectetur sit amet ornare suscipit, porta et erat. Donec nec nisi in nibh commodo laoreet. Mauris dapibus justo ut feugiat malesuada. Fusce ultricies ante tortor, non vestibulum est feugiat ut.</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"artist_sig\"><img src=\"images/sig.png\" alt=\"\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"single_player_container d-flex flex-column align-items-start justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"single_player\">\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"jplayer_2\" class=\"jp-jplayer\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"jp_container_2\" class=\"jp-audio\" role=\"application\" aria-label=\"media player\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"jp-type-single\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"player_details d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-details\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div>playing</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-title\" aria-label=\"title\">&nbsp;</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-controls-holder ml-auto\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"jp-play\" tabindex=\"0\"></button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"player_controls\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-gui jp-interface d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-controls-holder time_controls d-flex flex-row align-items-center justify-content-start\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div><div class=\"jp-current-time\" role=\"timer\" aria-label=\"time\">&nbsp;</div></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-progress\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-seek-bar\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-play-bar\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div><div class=\"jp-duration ml-auto\" role=\"timer\" aria-label=\"duration\">&nbsp;</div></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-volume-controls d-flex flex-row align-items-center justify-content-start ml-auto\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"jp-mute\" tabindex=\"0\"></button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-volume-bar\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"jp-volume-bar-value\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"jp-no-solution\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Update Required</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tTo play the media you will need to either update your browser to a recent version or update your <a href=\"http://get.adobe.com/flashplayer/\" target=\"_blank\">Flash plugin</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- Extra -->\n");
      out.write("\n");
      out.write("\t<div class=\"extra\">\n");
      out.write("\t\t<div class=\"extra_container\">\n");
      out.write("\t\t\t<div class=\"background_image\" style=\"background-image:url(images/extra.jpg)\"></div>\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-9\">\n");
      out.write("\t\t\t\t\t\t<div class=\"extra_content d-flex flex-column align-items-start justify-content-center\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"extra_title\"><h1>Get your tickets now!</h1></div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"extra_text\">\n");
      out.write("\t\t\t\t\t\t\t\t<p>In vitae nisi aliquam, scelerisque leo a, volutpat sem. Vivamus rutrum dui fermentum eros hendrerit, id lobortis leo volutpat. Maecenas sollicitudin est in libero pretium interdum</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"extra_button\"><a href=\"#\">Buy Now</a></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\t\t\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<!-- 1:1 Contect Chat Center (Fixed Navigator) -->\n");
      out.write("\t<div class=\"div-button-chat\" onclick=\"gotoChat()\">\n");
      out.write("\t\t<div class=\"icon-chat-ball\"><i class=\"fas fa-comment-dots\"></i></div>\t\n");
      out.write("\t\t<div class=\"icon-chat-circle\"></div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<div class=\"div-modal-chat\">\n");
      out.write("\t\t<div class=\"modal-top\">\n");
      out.write("\t\t\t<div id=\"modal-title\">ê³ ê°ì¼í°</div>\n");
      out.write("\t\t\t<span></span>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<a href=\"#\" class=\"button-modal-close\" onclick=\"closeChat()\">X</a>\n");
      out.write("\t\t<iframe src=\"http://localhost:3000/\"></iframe>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- Footer -->\n");
      out.write("\n");
      out.write("\t<footer class=\"footer\">\n");
      out.write("\t\t<div class=\"footer_container d-flex flex-xl-row flex-column align-items-start justify-content-start\">\n");
      out.write("\t\t\t<div class=\"newsletter_container\">\n");
      out.write("\t\t\t\t<div class=\"newsletter_title\"><h2>Subscribe to our newsletter</h2></div>\n");
      out.write("\t\t\t\t<form action=\"#\" id=\"newsletter_form\" class=\"newsletter_form\">\n");
      out.write("\t\t\t\t\t<input type=\"email\" class=\"newsletter_input\" placeholder=\"Your E-mail\" required=\"required\">\n");
      out.write("\t\t\t\t\t<button class=\"newsletter_button\">Subscribe</button>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"footer_lists d-flex flex-sm-row  flex-column align-items-start justify-content-start ml-xl-auto\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Useful Links -->\n");
      out.write("\t\t\t\t<div class=\"footer_list\">\n");
      out.write("\t\t\t\t\t<div class=\"footer_list_title\">Useful Links</div>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"index.html\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"about.html\">About us</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Testimonials</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Music</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"blog.html\">News</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Mixtape -->\n");
      out.write("\t\t\t\t<div class=\"footer_list\">\n");
      out.write("\t\t\t\t\t<div class=\"footer_list_title\">Mixtape</div>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Music</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">PR & Marketing</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Contact</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">About us</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Testimonials</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Connect -->\n");
      out.write("\t\t\t\t<div class=\"footer_list\">\n");
      out.write("\t\t\t\t\t<div class=\"footer_list_title\">Connect</div>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Returns</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Shippings</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Jobs</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Social Media</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Soundcloud</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"copyright_bar\">\n");
      out.write("\t\t\t<span><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("</span>\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"resources/js/jquery-3.2.1.min.js\"></script>\n");
      out.write("<script src=\"resources/styles/bootstrap-4.1.2/popper.js\"></script>\n");
      out.write("<script src=\"resources/styles/bootstrap-4.1.2/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"resources/plugins/greensock/TweenMax.min.js\"></script>\n");
      out.write("<script src=\"resources/plugins/greensock/TimelineMax.min.js\"></script>\n");
      out.write("<script src=\"resources/plugins/scrollmagic/ScrollMagic.min.js\"></script>\n");
      out.write("<script src=\"resources/plugins/greensock/animation.gsap.min.js\"></script>\n");
      out.write("<script src=\"resources/plugins/greensock/ScrollToPlugin.min.js\"></script>\n");
      out.write("<script src=\"resources/plugins/OwlCarousel2-2.2.1/owl.carousel.js\"></script>\n");
      out.write("<script src=\"resources/plugins/easing/easing.js\"></script>\n");
      out.write("<script src=\"resources/plugins/progressbar/progressbar.min.js\"></script>\n");
      out.write("<script src=\"resources/plugins/parallax-js-master/parallax.min.js\"></script>\n");
      out.write("<script src=\"resources/plugins/jPlayer/jquery.jplayer.min.js\"></script>\n");
      out.write("<script src=\"resources/plugins/jPlayer/jplayer.playlist.min.js\"></script>\n");
      out.write("<script src=\"resources/js/custom.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
