DROP SEQUENCE FREEBOARD_SEQ;  
DROP TABLE FREEBOARD;

CREATE SEQUENCE FREEBOARD_SEQ;

CREATE TABLE FREEBOARD(
   FREEBOARD_NUM NUMBER PRIMARY KEY,
   FREEBOARD_ID VARCHAR2(500) NOT NULL,
   FREEBOARD_TITLE VARCHAR2(500) NOT NULL,
   FREEBOARD_CONTENT CLOB NOT NULL,
   FREEBOARD_FILE CLOB,
   FREEBOARD_REGDATE DATE NOT NULL
);

INSERT INTO FREEBOARD
VALUES(FREEBOARD_SEQ.NEXTVAL,'이영한','테스트중입니다..','�궗湲� 移섏� 留먯옄.',SYSDATE);
VALUES(FREEBOARD_SEQ.NEXTVAL,'조수연','안녕하세요','너무힘들어요',SYSDATE);

VALUES(FREEBOARD_SEQ.NEXTVAL,'이영한','하하하하하하.','하하하하.',SYSDATE);

VALUES(FREEBOARD_SEQ.NEXTVAL,'조수연','안녕하세요','너무힘들어요',SYSDATE);

VALUES(FREEBOARD_SEQ.NEXTVAL,'이영한','테스트중입니다..','�궗湲� 移섏� 留먯옄.',SYSDATE);

VALUES(FREEBOARD_SEQ.NEXTVAL,'조수연','안녕하세요','너무힘들어요',SYSDATE);
SELECT * FROM FREEBOARD;
--market

DROP SEQUENCE MARKET_SEQ;  
DROP TABLE MARKET;

CREATE SEQUENCE MARKET_SEQ;

CREATE TABLE MARKET(
   MARKET_NUM NUMBER PRIMARY KEY,
   MARKET_ID VARCHAR2(500) NOT NULL,
   MARKET_TITLE VARCHAR2(500) NOT NULL,
   MARKET_CONTENT CLOB NOT NULL,
   MARKET_REGDATE DATE NOT NULL
);

INSERT INTO MARKET
VALUES(MARKET_SEQ.NEXTVAL,'조수연','안녕하세요','너무힘들어요',SYSDATE);
SELECT * FROM MARKET;