DROP TABLE FREEBOARD_COMMENT;
DROP SEQUENCE FREEBOARD_COMMENT_SEQ;

CREATE SEQUENCE FREEBOARD_COMMENT_SEQ;

CREATE TABLE FREEBOARD_COMMENT(
FREEBOARD_NUM VARCHAR2(1000) NOT NULL,
FREEBOARD_COMMENT_NUM NUMBER NOT NULL,
FREEBOARD_COMMENT_CONTENT VARCHAR2(1000) NOT NULL,
FREEBOARD_COMMENT_REGDATE DATE NOT NULL,
FREEBOARD_ID VARCHAR2(1000) NOT NULL
)

INSERT INTO FREEBOARD_COMMENT 
VALUES(1,FREEBOARD_COMMENT_SEQ.NEXTVAL,'안녕.',SYSDATE,'조수연');

SELECT FREEBOARD_NUM, FREEBOARD_COMMENT_NUM, FREEBOARD_COMMENT_CONTENT, FREEBOARD_COMMENT_REGDATE,FREEBOARD_ID
FROM FREEBOARD_COMMENT 
WHERE FREEBOARD_NUM = (SELECT FREEBOARD_NUM FROM FREEBOARD WHERE FREEBOARD_NUM = 1)
ORDER BY FREEBOARD_COMMENT_NUM;

INSERT INTO FREEBOARD_COMMENT
VALUES(1,FREEBOARD_COMMENT_SEQ.NEXTVAL,'22',SYSDATE,FREEBOARD_ID);

SELECT * FROM FREEBOARD_COMMENT;

INSERT INTO FREEBOARD_COMMENT
VALUES(#{freeboard_num},FREEBOARD_COMMENT_SEQ.NEXTVAL,#{freeboard_comment_content},SYSDATE,#{freeboard_id});

--market comment
DROP TABLE MARKET_COMMENT;
DROP SEQUENCE MARKET_COMMENT_SEQ;

CREATE SEQUENCE MARKET_COMMENT_SEQ;

CREATE TABLE MARKET_COMMENT(
MARKET_NUM VARCHAR2(1000) NOT NULL,
MARKET_COMMENT_NUM NUMBER NOT NULL,
MARKET_COMMENT_CONTENT VARCHAR2(1000) NOT NULL,
MARKET_COMMENT_REGDATE DATE NOT NULL,
MARKET_ID VARCHAR2(1000) NOT NULL
)

INSERT INTO MARKET_COMMENT 
VALUES(1,MARKET_COMMENT_SEQ.NEXTVAL,'안녕.',SYSDATE,'조수연');

SELECT MARKET_NUM, MARKET_COMMENT_NUM, MARKET_COMMENT_CONTENT, MARKET_COMMENT_REGDATE,MARKET_ID
FROM MARKET_COMMENT 
WHERE MARKET_NUM = (SELECT MARKET_NUM FROM MARKET WHERE MARKET_NUM = 1)
ORDER BY MARKET_COMMENT_NUM;

INSERT INTO MARKET_COMMENT
VALUES(1,MARKET_COMMENT_SEQ.NEXTVAL,'22',SYSDATE,MARKET_ID);

SELECT * FROM MARKET_COMMENT;

INSERT INTO MARKET_COMMENT
VALUES(#{market_num},MARKET_COMMENT_SEQ.NEXTVAL,#{market_comment_content},SYSDATE,#{market_id});