DROP SEQUENCE FREEBOARD_SEQ;  
DROP TABLE FREEBOARD;

CREATE SEQUENCE FREEBOARD_SEQ;

CREATE TABLE FREEBOARD(
   FREEBOARD_NUM NUMBER PRIMARY KEY,
   FREEBOARD_ID VARCHAR2(500) NOT NULL,
   FREEBOARD_TITLE VARCHAR2(500) NOT NULL,
   FREEBOARD_CONTENT CLOB NOT NULL,
   FREEBOARD_REGDATE DATE NOT NULL
);

INSERT INTO FREEBOARD
VALUES(FREEBOARD_SEQ.NEXTVAL,'이영한','하하하하하하.','하하하하.',SYSDATE);
SELECT * FROM FREEBOARD;