DROP TABLE FREEBOARD_COMMENT;
DROP SEQUENCE FREEBOARD_COMMENT_SEQ;

--寃뚯떆湲�踰덊샇,�뙎湲�踰덊샇,�뙎湲��궡�슜,�뙎湲��옉�꽦�씪,�븘�씠�뵒
CREATE SEQUENCE FREEBOARD_COMMENT_SEQ;


CREATE TABLE FREEBOARD_COMMENT(
FREEBOARD_NUM VARCHAR2(1000) NOT NULL,
FREEBOARD_COMMENT_NUM NUMBER NOT NULL,
FREEBOARD_COMMENT_CONTENT VARCHAR2(1000) NOT NULL,
FREEBOARD_COMMENT_REGDATE DATE NOT NULL,
FREEBOARD_ID VARCHAR2(1000) NOT NULL
)

INSERT INTO FREEBOARD_COMMENT 
VALUES(1,FREEBOARD_COMMENT_SEQ.NEXTVAL,FREEBOARD_CO_COMMENT_SEQ.NEXTVAL,'TEST.',SYSDATE,'이영한');

SELECT FREEBOARD_NUM, FREEBOARD_COMMENT_NUM, FREEBOARD_COMMENT_CONTENT, FREEBOARD_COMMENT_REGDATE,FREEBOARD_ID
FROM FREEBOARD_COMMENT 
WHERE FREEBOARD_NUM = (SELECT FREEBOARD_NUM FROM FREEBOARD WHERE FREEBOARD_NUM = 1)
ORDER BY FREEBOARD_COMMENT_NUM;

INSERT INTO FREEBOARD_COMMENT
VALUES(1,FREEBOARD_COMMENT_SEQ.NEXTVAL,'Test以묒엯�땲�떎.',SYSDATE,FREEBOARD_ID);

SELECT * FROM FREEBOARD_COMMENT;

INSERT INTO FREEBOARD_COMMENT
VALUES(#{freeboard_num},FREEBOARD_COMMENT_SEQ.NEXTVAL,#{freeboard_comment_content},SYSDATE,#{freeboard_id});