DROP SEQUENCE FREEBOARD_SEQ;  
DROP TABLE FREEBOARD;

CREATE SEQUENCE FREEBOARD_SEQ;

CREATE TABLE FREEBOARD(
   FREEBOARD_NUM NUMBER PRIMARY KEY,
   FREEBOARD_ID VARCHAR2(500) NOT NULL,
   FREEBOARD_TITLE VARCHAR2(500) NOT NULL,
   FREEBOARD_CONTENT CLOB NOT NULL,
   FREEBOARD_REGDATE DATE NOT NULL
);

INSERT INTO FREEBOARD
<<<<<<< HEAD
VALUES(FREEBOARD_SEQ.NEXTVAL,'이영한','하하하하하하.','하하하하.',SYSDATE);
=======
VALUES(FREEBOARD_SEQ.NEXTVAL,'조수연','안녕하세요','너무힘들어요',SYSDATE);
>>>>>>> 90219b2927a2dd579bed33599a634421a82f45b1
SELECT * FROM FREEBOARD;