/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2019-08-08 01:35:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.market;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class heartShop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1565093400000L));
    _jspx_dependants.put("jar:file:/Users/zsoo/Documents/Workspace_Final/clone_final/DolDuck_TeamProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/dolduck_project/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/Users/zsoo/Documents/Workspace_Final/clone_final/DolDuck_TeamProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/dolduck_project/WEB-INF/lib/spring-security-taglibs-5.1.3.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1547128166000L));
    _jspx_dependants.put("/WEB-INF/views/market/../footer.jsp", Long.valueOf(1564893408000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-5.1.3.RELEASE.jar", Long.valueOf(1565093391000L));
    _jspx_dependants.put("/WEB-INF/views/market/../header.jsp", Long.valueOf(1565227206000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>All About K-POP! - Shop</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"description\" content=\"Mixtape template project\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"resources/styles/bootstrap-4.1.2/bootstrap.min.css\">\n");
      out.write("<link\n");
      out.write("\thref=\"resources/plugins/font-awesome-4.7.0/css/font-awesome.min.css\"\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"resources/plugins/OwlCarousel2-2.2.1/owl.carousel.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"resources/plugins/OwlCarousel2-2.2.1/owl.theme.default.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"resources/plugins/OwlCarousel2-2.2.1/animate.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"resources/styles/main_styles.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"resources/styles/responsive.css\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<title>Header</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- Header -->\n");
      out.write("\t<header class=\"header\">\n");
      out.write("\t\t<section\n");
      out.write("\t\t\tclass=\"header_content d-flex flex-row align-items-center justify-content-center\">\n");
      out.write("\t\t\t<div class=\"logo\">\n");
      out.write("\t\t\t\t<a href=\"home.do\">DOL-Duck</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"log_reg\">\n");
      out.write("\t\t\t\t<ul class=\"d-flex flex-row align-items-start justify-content-start\">\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_sec_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/join.do\">Register</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<nav class=\"main_nav\">\n");
      out.write("\t\t\t\t<ul class=\"d-flex flex-row align-items-start justify-content-start\">\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"home.do\">HOME</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"youtube.do\">YouTube</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"vote.do\">Vote</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"chart.do\">Music Chart</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">LIVE</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Board</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a href=\"heartShop.do\"\n");
      out.write("\t\t\t\t\t\tclass=\"dropdown-toggle\" data-toggle=\"dropdown\">Market</a>\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-item:hover\"><a href=\"heartShop.do\">heartShop</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown-item:hover\"><a href=\"Goodies.do\">Goodies</a></li>\n");
      out.write("\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t<li class=\"form-group has-search\">\n");
      out.write("\t\t\t\t\t\t<span class=\"fa fa-search form-control-feedback\"></span> \n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Search\">\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t\t<div class=\"hamburger ml-auto\">\n");
      out.write("\t\t\t\t<div\n");
      out.write("\t\t\t\t\tclass=\"d-flex flex-column align-items-end justify-content-between\">\n");
      out.write("\t\t\t\t\t<div></div>\n");
      out.write("\t\t\t\t\t<div></div>\n");
      out.write("\t\t\t\t\t<div></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</section>\n");
      out.write("\t</header>\n");
      out.write("\t<!-- Menu -->\n");
      out.write("\n");
      out.write("\t<section class=\"menu\">\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<div class=\"menu_overlay\"></div>\n");
      out.write("\t\t\t<div\n");
      out.write("\t\t\t\tclass=\"menu_container d-flex flex-column align-items-start justify-content-center\">\n");
      out.write("\t\t\t\t<div class=\"menu_log_reg\">\n");
      out.write("\t\t\t\t\t<ul class=\"d-flex flex-row align-items-start justify-content-start\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"loginform.do\">Login</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Register</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<nav class=\"menu_nav\">\n");
      out.write("\t\t\t\t\t<ul\n");
      out.write("\t\t\t\t\t\tclass=\"d-flex flex-column align-items-start justify-content-start\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"home.do\">HOME</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"youtube.do\">You Tube</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"vote.do\">Vote</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"chart.do\">Music Chart</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">LIVE</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Board</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"heartShop.do\">heartShop</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"Goodies.do\">Goodies</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</nav>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("</body>\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/home.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\n");
      out.write("<script src=\"resources/styles/bootstrap-4.1.2/popper.js\"></script>\n");
      out.write("<script src=\"resources/styles/bootstrap-4.1.2/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"resources/plugins/greensock/TweenMax.min.js\"></script>\n");
      out.write("<script src=\"resources/plugins/greensock/TimelineMax.min.js\"></script>\n");
      out.write("<script src=\"resources/plugins/scrollmagic/ScrollMagic.min.js\"></script>\n");
      out.write("<script src=\"resources/plugins/greensock/animation.gsap.min.js\"></script>\n");
      out.write("<script src=\"resources/plugins/greensock/ScrollToPlugin.min.js\"></script>\n");
      out.write("<script src=\"resources/plugins/OwlCarousel2-2.2.1/owl.carousel.js\"></script>\n");
      out.write("<script src=\"resources/plugins/easing/easing.js\"></script>\n");
      out.write("<script src=\"resources/plugins/progressbar/progressbar.min.js\"></script>\n");
      out.write("<script src=\"resources/plugins/parallax-js-master/parallax.min.js\"></script>\n");
      out.write("<script src=\"resources/plugins/jPlayer/jquery.jplayer.min.js\"></script>\n");
      out.write("<script src=\"resources/plugins/jPlayer/jplayer.playlist.min.js\"></script>\n");
      out.write("<script src=\"resources/js/custom.js\"></script>\n");
      out.write("<script src=\"https://d3js.org/d3.v4.min.js\"></script>\n");
      out.write("<script src=\"https://kit.fontawesome.com/c1455fa856.js\"></script>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"container market\">\n");
      out.write("\t\n");
      out.write("\t\t\n");
      out.write("\t\t<h1> Market </h1>\n");
      out.write("\t\t<ul class=\"nav nav-tabs market_ul\">\n");
      out.write("\t\t\t<li class=\"nav-item\">\n");
      out.write("\t\t\t\t<a class=\"nav-link market_link\" href=\"heartShop.do\">HeartShop</a>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<li class=\"nav-item\">\n");
      out.write("\t\t\t\t<a class=\"nav-link market_link\" href=\"Goodies.do\">Goodies</a>\n");
      out.write("\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t<div class=\"col-md-10 market_border\">\n");
      out.write("\t\t\t<div class=\"heartShop\">\n");
      out.write("\t\t\t\t<div class=\"heartShop-item-title\"><span>하트존</span></div>\n");
      out.write("\t\t\t\t<ul class=\"\">\n");
      out.write("\t\t\t\t\t<li class=\"heartShop-item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-img\"><img class=\"heart_size\"src=\"resources/images/heart.png\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-subject\">하트 10개</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-button\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"btn btn-buy-item\">1,000원\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"item-price-heart\" value=\"1000\">\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"heartShop-item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-img\"><img class=\"heart_size\"src=\"resources/images/heart.png\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-subject\">하트 20+1개</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-button\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"btn btn-buy-item\">2,000원\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"item-price-heart\" value=\"2000\">\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"heartShop-item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-img\"><img class=\"heart_size\"src=\"resources/images/heart.png\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-subject\">하트 50+5개</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-button\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"btn btn-buy-item\">5,000원\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"item-price-heart\" value=\"5000\">\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"heartShop-item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-img\"><img class=\"heart_size\"src=\"resources/images/heart.png\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-subject\">하트 100+10개</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-button\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"btn btn-buy-item\">10,000원\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"item-price-heart\" value=\"10000\">\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<div class=\"heartShop-item-title\"><span>투표권</span></div>\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li class=\"heartShop-item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-img\"><img src=\"https://www.bestidol.co.kr/assets/image/icon/store/store-item-vote.png\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-subject\">투표권 1개</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-button\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"btn btn-buy-item\"><i class=\"fas fa-heart\"></i>&nbsp;5\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"item-price-vote\" value=\"5\">\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"heartShop-item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-img\"><img src=\"https://www.bestidol.co.kr/assets/image/icon/store/store-item-vote.png\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-subject\">투표권 11개</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-button\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"btn btn-buy-item\"><i class=\"fas fa-heart\"></i>&nbsp;50\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"item-price-vote\" value=\"50\">\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"heartShop-item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-img\"><img src=\"https://www.bestidol.co.kr/assets/image/icon/store/store-item-vote.png\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-subject\">투표권 55개</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-button\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"btn btn-buy-item\"><i class=\"fas fa-heart\"></i>&nbsp;250\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"item-price-vote\" value=\"250\">\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"heartShop-item\">\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-img\"><img src=\"https://www.bestidol.co.kr/assets/image/icon/store/store-item-vote.png\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-subject\">투표권 120개</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"vote-area-button\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"btn btn-buy-item\"><i class=\"fas fa-heart\"></i>&nbsp;500\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"item-price-vote\" value=\"500\">\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\t\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<script src=\"\" type=\"text/javascript\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t$({\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t})\n");
      out.write("\t\t</script>\t\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"description\" content=\"Mixtape template project\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("</head>\n");
      out.write("<title>Footer</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("   <!-- Footer -->\n");
      out.write("\n");
      out.write("   <footer class=\"footer\">\n");
      out.write("      <div class=\"footer_container d-flex flex-xl-row flex-column align-items-start justify-content-start\">\n");
      out.write("         <div class=\"newsletter_container\">\n");
      out.write("            <div class=\"newsletter_title\"><h2>Subscribe to our newsletter</h2></div>\n");
      out.write("            <form action=\"#\" id=\"newsletter_form\" class=\"newsletter_form\">\n");
      out.write("               <input type=\"email\" class=\"newsletter_input\" placeholder=\"Your E-mail\" required=\"required\">\n");
      out.write("               <button class=\"newsletter_button\">Subscribe</button>\n");
      out.write("            </form>\n");
      out.write("         </div>\n");
      out.write("         <div class=\"footer_lists d-flex flex-sm-row  flex-column align-items-start justify-content-start ml-xl-auto\">\n");
      out.write("\n");
      out.write("            <!-- Useful Links -->\n");
      out.write("            <div class=\"footer_list\">\n");
      out.write("               <div class=\"footer_list_title\">Useful Links</div>\n");
      out.write("               <ul>\n");
      out.write("                  <li><a href=\"index.html\">Home</a></li>\n");
      out.write("                  <li><a href=\"about.html\">About us</a></li>\n");
      out.write("                  <li><a href=\"#\">Testimonials</a></li>\n");
      out.write("                  <li><a href=\"#\">Music</a></li>\n");
      out.write("                  <li><a href=\"blog.html\">News</a></li>\n");
      out.write("               </ul>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Mixtape -->\n");
      out.write("            <div class=\"footer_list\">\n");
      out.write("               <div class=\"footer_list_title\">Mixtape</div>\n");
      out.write("               <ul>\n");
      out.write("                  <li><a href=\"#\">Music</a></li>\n");
      out.write("                  <li><a href=\"#\">PR & Marketing</a></li>\n");
      out.write("                  <li><a href=\"#\">Contact</a></li>\n");
      out.write("                  <li><a href=\"#\">About us</a></li>\n");
      out.write("                  <li><a href=\"#\">Testimonials</a></li>\n");
      out.write("               </ul>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Connect -->\n");
      out.write("            <div class=\"footer_list\">\n");
      out.write("               <div class=\"footer_list_title\">Connect</div>\n");
      out.write("               <ul>\n");
      out.write("                  <li><a href=\"#\">Returns</a></li>\n");
      out.write("                  <li><a href=\"#\">Shippings</a></li>\n");
      out.write("                  <li><a href=\"#\">Jobs</a></li>\n");
      out.write("                  <li><a href=\"#\">Social Media</a></li>\n");
      out.write("                  <li><a href=\"#\">Soundcloud</a></li>\n");
      out.write("               </ul>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"copyright_bar\">\n");
      out.write("         <span><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("</span>\n");
      out.write("      </div>\n");
      out.write("   </footer>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/market/../header.jsp(42,5) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("isAnonymous()");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("\t\t\t\t\t\t<li><a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/login.do\">Login</a></li>\n");
        out.write("\t\t\t\t\t");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/market/../header.jsp(45,5) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("\t\t\t\t\t\t<li><a href=\"logout.do\">Logout</a></li>\n");
        out.write("\t\t\t\t\t");
      }
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
    }
    return false;
  }
}
